
 const POST_TYPES = {
    FITCH_POST_START : "FITCH_POST_START",
    FITCH_POST_SUCSESS : "FITCH_POST_SUCESS",
    FITCH_POST_FAIL : "FITCH_POST_FAIL",
    ADD_POST : "ADD_POST",
    ADD_COMMENT : "ADD_COMMENT"

}


export default POST_TYPES;